### ISSUE TITLE
Compression worse than with the WebP format

### ISSUE THREAD

**Issue by nilsonbazana** [0xC0000054/avif-format#9] opened 2022-12-06 00:11 UTC
Upon saving some photos directly from a JPEG file as AVIF on Photoshop CC 2014, the compression ratio I got is, if not too close to WebP's, worse than it.

In comparison, if I use the AVIF compression implementation offered on XnviewMP image viewer with the same parameters (4-4-2, lossy alpha, 80-mark quality) the compression is around 8% from JPEG's original size! 
WebP in comparison, yields around 50% or more - way more in accordance to the expected difference in compression between these two formats.

**Comment by gregbenz** [comment] 2022-12-06 01:38
Is "quality" an official part of the spec (ie the numbers have a fixed meaning), or open to interpretation between different implementations of AVIF encoders?

There are other potential factors within the spec, such as the encoder effort, that could influence size. Bit depth is a big one, so you'd want to make sure other variables are held constant for the comparison.

**Comment by 0xC0000054** [comment] 2022-12-06 06:31
> Is "quality" an official part of the spec (ie the numbers have a fixed meaning), or open to interpretation between different implementations of AVIF encoders?

The "quality" value is open to interpretation between encoder implementations.

Internally AOM uses a quality range where 0 is the best and 63 is the worst (this range may be from the AV1 spec, I'm not sure), the encoders that use AOM are free to pick how they map that to the standard [0, 100] range.
There are also a bunch of other encoder settings that may influence the encoding behavior.
Other AV1 encoders (e.g. rav1e or svt) may have different settings and/or defaults than AOM.

XnviewMP appears to be using libavif, I do not know what encoder it is configured to use.
Looking at the source code for the libheif AOM encoder plugin, it appears to be simultaneously using 2 different methods of setting the encoder quality. 😕 
I have no idea how those 2 methods would interact.

**Comment by 0xC0000054** [comment] 2022-12-07 00:25
It appears that the next version of libavif will have the option to use a similar quality value to libheif, with the quality value in the [0, 100] range. 
The current version uses min and max quantization values, which is a lower-level mechanism for configuring the encoder quality.

> In comparison, if I use the AVIF compression implementation offered on XnviewMP image viewer with the same parameters (4-4-2, lossy alpha, 80-mark quality) the compression is around 8% from JPEG's original size!

What version of XNViewMP are you using?
Version 1.3.1 does not have a quality slider for AVIF, its save UI options only provide the min and max quantization values that I mentioned above.

**Comment by 0xC0000054** [comment] 2022-12-07 01:17
> Do you expect avif-format will show significantly different image results at the same quality with that updated library?

I do not.
It appears that the new libavif code uses the same quantization values and quality range mapping algorithm as libheif.
But libavif users will have to update their code to take advantage of the new option.

**Comment by gregbenz** [comment] 2022-12-07 02:05
Friendly for the dev? I'm just thinking about your interface, which has just the quality slider and is pretty simple. I'm assuming you mean quantization settings you set in your code but don't expose in your UI.

**Comment by gregbenz** [comment] 2022-12-07 14:25
Gotcha, thanks.

**Comment by nilsonbazana** [comment] 2022-12-07 20:34
> What version of XNViewMP are you using? Version 1.3.1 does not have a quality slider for AVIF, its save UI options only provide the min and max quantization values that I mentioned above.
> 
> ![XNViewMP AVIF save options](https://user-images.githubusercontent.com/26996983/206057048-03651fea-5023-4b8c-9ca8-d905533d8bff.png)

Sorry for the late reply. 

I've used version 1.3 for that - with, you're right, no quality settings whatsoever, so my mistake (I may have got it mixed up in my mind regarding such settings with some WebP settings I was fiddling with).

**Comment by 0xC0000054** [comment] 2022-12-07 23:16
I made the same mistake with the XNViewMP JPEG quality settings.

Closing this issue as it is not a bug in the plugin.

**Closed by 0xC0000054** 2022-12-07 23:16 UTC
